trigger:
  branches:
    include:
      - develop

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployToHostingerVPS
  displayName: 'Deploy to Hostinger VPS'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: SSH@0
    inputs:
      sshEndpoint: '$(HOSTINGER_SSH_HOST)'
      username: '$(HOSTINGER_SSH_USERNAME)'
      password: '$(HOSTINGER_SSH_PASSWORD)'
      runOptions: 'commands'
      commands: |
        cd Amg-ingressos-aqui-eventos-api
        git checkout develop
        git pull
        docker stop eventos-ticket-test
        docker rm eventos-ticket-test
        docker build -t eventos-ticket .
        docker run -d -p 8080:80 eventos-ticket-test
