# Trigger do pipeline. Defina quando o pipeline deve ser acionado.
trigger:
  branches:
    include:
      - main
      - develop  # Se você tiver uma branch de desenvolvimento, inclua-a aqui

# Etapas do pipeline
jobs:
  - job: Build
    displayName: Build .NET Application
    pool:
      vmImage: 'windows-latest'  # Usaremos o ambiente Windows para construir a aplicação .NET, mas você pode escolher outro ambiente se preferir.

    steps:
      - task: UseDotNet@2  # Essa tarefa define a versão do .NET a ser usada no build.
        displayName: 'Use .NET SDK'  # Nome exibido na tarefa
        inputs:
          packageType: 'sdk'
          version: '7.x'

      - script: dotnet restore  # Restaura as dependências do projeto
        displayName: 'Restore'

      - script: dotnet build --configuration Release  # Executa o build da aplicação
        displayName: 'Build'
